# The individual Redis nodes, denoted as host + ':' + port
spring:
  redis:
    cluster:
      nodes: capacity-info-cache-0001-001.y0cxg2.0001.euw2.cache.amazonaws.com:6379,
             capacity-info-cache-0001-002.y0cxg2.0001.euw2.cache.amazonaws.com:6379,
             capacity-info-cache-0001-003.y0cxg2.0001.euw2.cache.amazonaws.com:6379,
             capacity-info-cache-0002-001.y0cxg2.0001.euw2.cache.amazonaws.com:6379,
             capacity-info-cache-0002-002.y0cxg2.0001.euw2.cache.amazonaws.com:6379,
             capacity-info-cache-0002-003.y0cxg2.0001.euw2.cache.amazonaws.com:6379,
             capacity-info-cache-0003-001.y0cxg2.0001.euw2.cache.amazonaws.com:6379,
             capacity-info-cache-0003-002.y0cxg2.0001.euw2.cache.amazonaws.com:6379,
             capacity-info-cache-0003-003.y0cxg2.0001.euw2.cache.amazonaws.com:6379